### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by Nicolaswg** [carloshs1994/AwesomeBooks#3]
# Congratulation 
🦅 

> You have done an awesome work 👍 

## Recomendation

- We think that is better to create a global function for deleting the book's elements from the DOM and the LocalStorage.

**Comment by IbrohimRasulov** [comment]
Good job overall 👍 👍 👍  I recommend you to organize your code with better logic 😁

**Comment by carloshs1994** [comment]
# Solved!
<img src="https://media1.giphy.com/media/3NtY188QaxDdC/giphy.gif"/>
